### ISSUE TITLE
React Native setup

### ISSUE THREAD

**Issue by jonathan-irvin** [two-jelly-beans/jelly-fin#21]

**Comment by jonathan-irvin** [comment]
I just rolled back my cleanup changes pending this issue to be resolved.  It's important to have the project in a working state, no matter what.

**Comment by jonathan-irvin** [comment]
@emmanuelvr thanks for pushing your code, what else is needed?

**Comment by emmanuelvr** [comment]
We need to setup Flow, linter and testing with React Native.
I'm updating the README file with the requirements to build the app.

**Comment by emmanuelvr** [comment]
README file updated

**Comment by jonathan-irvin** [comment]
Looking good so far, I want to combine the package.json and make for a unified experience.

I'm of the notion that the package.json should have everything you need to get started.  This will help people contribute if the Mean Time To Contribute (MTTC) is minimal.  Developer setup is a pain so the quicker we can get someone setup then the quicker they can knock out some code.

**Comment by emmanuelvr** [comment]
I completely agree with you. I just remembered, the navigation must also be set up.
If you could merge the app folder with the root, it'd be nice. I can do that part and also set up the linter, Flow and the navigation. For the navigation I intend to use react-navigation.
