### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by djbeadle** [two-jelly-beans/jelly-fin#22]
**Describe the bug**
npm start fails on macOS

**To Reproduce**
1. cloned the repo
2. npm install
3. brew install watchman
4. npm start... error occurs

**Log**
```shell
> jelly-fin@0.1.0 start /Users/Djbeadle/Documents/jelly-fin
> react-native-scripts start

6:12:45 PM: Starting packager...
***ERROR STARTING PACKAGER***

Error: Missing app.json. See https://docs.expo.io/
6:12:46 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1329:11
    at next (native)
    at step (/Users/Djbeadle/Documents/jelly-fin/node_modules/xdl/build/Project.js:1735:191)
    at /Users/Djbeadle/Documents/jelly-fin/node_modules/xdl/build/Project.js:1735:361
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jonathan-irvin** [comment]
Hey! Thanks for calling it out.  This depends on #21 since we are literally setting up the project from scratch.

**Comment by jonathan-irvin** [comment]
Come join us on discord if you haven't already https://discord.gg/xveZ3FT

**Comment by jonathan-irvin** [comment]
@djbeadle I'm walking this back a bit while we wait on configuration changes.  It's important to have a green build, no matter what.

I've just reverted some changes I've made to bring the build back to a working state.  Pull down the latest changes.  It should work for you now.
