### ISSUE TITLE
Add a package.json script to setup development environment

### ISSUE THREAD

**Issue by jonathan-irvin** [two-jelly-beans/jelly-fin#26]
Development setup is always a pain point.  I need someone to take that, script it, and put it nicely into a `npm run setup` script in package.json.

What would also be nice is a sister script that checks global script versions to make sure you have everything you need.

**Comment by misterhtmlcss** [comment]
This is assigned 'good first issue', but if no one outside of @jonathan-irvin or @emmanuelvr has actually gotten the software run, then it seems not a good first issue. Should we remove the 'help wanted' and 'good first issue'?

**Comment by jonathan-irvin** [comment]
@misterhtmlcss fair point.

**Comment by jonathan-irvin** [comment]
Fixed in #56
