### ISSUE TITLE
Build process for Travis

### ISSUE THREAD

**Issue by jonathan-irvin** [two-jelly-beans/jelly-fin#27]
Since we will be building on iOS and Android, Travis should automate that build process for us.

**Comment by emmanuelvr** [comment]
Does this mean deployment process? I'd like to set that up. How do I use Travis to do this?

**Comment by jonathan-irvin** [comment]
1. We need to know how to deploy manually for testing and production.
2. We can take those steps and toss them in Travis.yml.  I would check the docs on that.
