### ISSUE TITLE
Dockerize our setup to lower support frequency/issues during onboarding of team members

### ISSUE THREAD

**Issue by misterhtmlcss** [two-jelly-beans/jelly-fin#36]
Currently we all operate on different platforms and different hardware and software versions and we need to standardize as much as we can to ensure our build process is more reliable especially for newer contributors.

Feedback?

**Comment by jonathan-irvin** [comment]
I think this is a worthy effort and will simplify things down the road.

A quick google and I pulled up this article: [Docker and Development Environments: Setting up for Node.js on MacOS](http://activelamp.com/blog/devops/docker-and-development-environments-setting-up-for-nodejs-on-osx/)

**Comment by jonathan-irvin** [comment]
I'm starting work on this now

**Comment by misterhtmlcss** [comment]
Sounds good. Let us know if you need help then.

**Comment by jonathan-irvin** [comment]
I didn't mean to step on toes, but wanted to help.  You guys can pick up where I left off on the `docker` branch.
