### ISSUE TITLE
Desktop/web version?

### ISSUE THREAD

**Issue by 44r0n** [two-jelly-beans/jelly-fin#48]
**Is your feature request related to a problem? Please describe.**
First of all, I don't know if it's aleady planned or in mind.
We all know mobile devices are the most used for consume everithing. But what about if I am in front of my computer and want to use jelly-fin, should I switch to mobile?

**Describe the solution you'd like**
Other solution could be provided. Why not a desktop app or web app I could use in order to switch?? 

**Describe alternatives you've considered**
[Electron](https://electronjs.org/) with [React](https://reactjs.org/) could be considered for the desktop and only [React](https://reactjs.org/) for web IMO.

**Comment by jonathan-irvin** [comment]
@44r0n yes, I definitely want to do a web version.  Right now it feels like we could get one going faster than our current iteration for our app. (We're running into a ton of build issues that need to be resolved).

Thanks for submitting!

**Comment by jonathan-irvin** [comment]
I would say since we're going with React Native for mobile we could use React or VueJS for the web.

The mobile app is definitely needed to take the information on the go, but I'd argue that a web version might be more viable since people (when they do bills) are usually sitting down at a desk and planning it out.  At least, that's how my wife does it.

**Comment by misterhtmlcss** [comment]
@jonathan-irvin do we want to close this as Vuejs or revise the issue to align with that decision and then re-label it to continue a related conversation to the project

**Comment by jonathan-irvin** [comment]
@misterhtmlcss I think we can close this.  We need to direct all feature requests and bugs to the https://github.com/jelly-fin/jelly-fin-web repo
